### ISSUE TITLE
Recordtype handling

### ISSUE THREAD

**Issue by dieffrei** [realestate-com-au/json-bourne-sfdx-cli#10]
#### Issue Description
I'm trying to export/import record types, but when records is created they doesnt have recordtypes assigned

    "CoverageZone__c": {
      "query": "SELECT Name, RecordType.DeveloperName, RecordType.Id, Description__c, ExternalCoverageName__c, Country__r.Iso2__c, MigrationId__c FROM CoverageZone__c",
      "externalid": "MigrationId__c",
      "directory": "coverageZones",
      "cleanupFields": [],
      "hasRecordTypes": true,
      "enableMultiThreading": true
    }

Do I need any another configuration?

#### Helpful Links

* [Example Link](www.url.com)

**Comment by aimaj** [comment]
Would it be possible to see an obfuscated sample json extracted from that table? Try removing "RecordType.Id" from the query, that value is org specific anyway (unless you are only moving between sandboxes under the same production org)

Thanks

**Comment by dieffrei** [comment]
@aimaj this is another sample
`{
  "CompanyType__c": "Partner",
  "MigrationId__c": "REC4Yv8Y7y23768426",
  "Name": "Provider Test",
  "Phone": null,
  "RecordType": {
    "DeveloperName": "Provider"
  },
  "SBQQ__ContractCoTermination__c": "Never",
  "SBQQ__PreserveBundle__c": true,
  "SBQQ__RenewalModel__c": null,
  "SBQQ__RenewalPricingMethod__c": "Same"
}`

Event the JSON seems correct the recordtype has not been assigned correctly.

Thanks in advance

**Comment by dieffrei** [comment]
@aimaj I fix the bug on PR #11

**Comment by dieffrei** [comment]
@ddawson235 could you take a look?

**Comment by ddawson235** [comment]
Fixed in merged PR
