### ISSUE TITLE
Getting Error 'Cannot read property 'replace' of undefined' on Export

### ISSUE THREAD

**Issue by adnan8387** [realestate-com-au/json-bourne-sfdx-cli#2]
#### Issue Description
I have installed the plugin and trying to export custom object with external id. I am getting'Cannot read property 'replace' of undefined' error.

**Comment by aimaj** [comment]
Hi adnan8387,

Would it be possible for you to provide the command being run, as well as the values under the "objects" key in your json configuration file? The entry specifying query, externalid etc. Sounds like it could be a problem with the object specification in that file.

Cheers

**Comment by adnan8387** [comment]
thanks aimaj for your prompt response.

**Command:** sfdx bourne:export -a -c data/reference_data/config.json

**Config file** 
{
    "pollTimeout": 30,
    "pullBatchSize": 150,
    "maxPollCount":60,
    "payloadLength":2999800,
    "useManagedPackage": true,
    "allObjects": [
        "Candidate__c"
    ],
    "objects": {
        "Candidate__c":{
            "query" : "SELECT Name, External_Id__c, Prospect_Rating__c FROM Candidate__c",
            "externalid" : "External_Id__c",
            "directory": "reference_data/Candidate__c",
            "filename": "Candidate__c",
            "cleanupFields": [],
            "hasRecordTypes": false
        }
    }
}

**Comment by ddawson235** [comment]
@adnan8387 I have managed to reproduce the error. It is a combination of a few things:

1) The `Filename` entry in the configuration file should relate to a field on the object, and you should ensure that it is always unique. The easiest way to accomplish this is to specify `External_ID__c` as the filename. It will set the json file extracted to the value of the field, so if the records external Id is `EXT123` then the file extracted for that record will be called `EXT123.json`.
2) You need to ensure that all records have a value in the External Id field. Easiest way to do this is either to add a query filter `WHERE External_Id__c ~= null` or you can ensure the record has a value using the example trigger specified in the README.

We may make some changes to the plugin to make the filename easier to configure as well as handle where the field specified as the filename field does not have a value (hence the extraction should fail).

Let us know if this resolves your issue.

**Comment by adnan8387** [comment]
Thanks @ddawson235, renaming the filename to be same as one of the field name resolved the issue.
