### ISSUE TITLE
Managed Package

### ISSUE THREAD

**Issue by dieffrei** [realestate-com-au/json-bourne-sfdx-cli#8]
Looks really great!
Any plans to make the managed package open source?

**Comment by dieffrei** [comment]
I just found, could be nice to mention it on the sfdx plugin documentation.
Is this repository right? 
https://github.com/realestate-com-au/json-bourne-sfdx-pkg

**Comment by ddawson235** [comment]
@dieffrei thanks for the feedback. I have raised a PR to make the other repo easier to find, but yes you are correct this is the open source code for the package side of the plugin.
